   export const SkillConstant = [
  "Thiên Địa Duy Ngã Đạo",
  "Thiên Lôi Đạo Ngã Kiếm",
  "Vạn Vật Thành Ngã Kiếm",
  "Càn Khôn Nhậm Ngã Hành",
  "Chúng Sinh Do Ngã Diệt",
  "Lưỡng Cực Đạn Ngã Kiếm",
  "Đoạt Mục Duy Sắc Diệt",
  "Kiếm Công Tung Hoành Hành",
  "Phi Long Tại Thiên",
  "Kiến Long Tại Điền",
  "Hồng Tiệm Vu Lục",
  "Tiềm Long Vật Dụng",
  "Lợi Thiệp Đại Xuyên",
  "Thần Long Bãi Vĩ",
  "Đột Như Kì Lai",
  "Song Long Thủ Thủy",
  "Thời Thừa Lục Long",
  "Long Chiến Tại Dã",
  "Lí Sương Băng Chí",
  "Kháng Long Hữu Hối",
  "Tả Hữu Thần Long",
  "Giao Long Phiên Giang",
  "Cuồng Long Loạn Vũ:",
  "Thần Long Hàng Thế",
  "Long Du Thiên Địa",
  "Long Đằng Ngũ Nhạc",
  "Phật Quang Sơ Hiện",
  "Kim Đỉnh Phật Đăng",
  "Phật Động Sơn Hà",
  "Phật Vấn Già Lam",
  "Nghênh Phật Tây Thiên:",
  "Phật Quang Phổ Chiếu",
  "Thiên Phật Hàng Thế ",
  "Phật Pháp Vô Biên",
  "Vạn Phật Triều Tông",
  "Bi thống mạc danh",
  "Mạc danh kỳ diệu",
  "Danh động nhất thời",
  "Kiếm hoả vô danh",
  "Danh bất hư truyền",
  "Mai danh ẩn tánh",
  "Nhất kiếm thành danh",
  "Oán phẫn mạc danh",
  "Kiếm quang sạ hiện",
  "Kiếm lạc cửu thiên",
  "Danh động giang hồ",
  "Kinh hàn nhất phách",
  "Băng phong tam xích",
  "Hồng hạnh xuất tường",
  "Đào chi yểu yểu",
  "Đạp tuyết tầm mai",
  "Lãnh nhật băng tâm",
  "Vô hình đạo",
  "Vô tình đạo",
  "Vô danh đạo",
  "Vô ngã đạo",
  "Lôi đình vô tận",
  "Phong hoả vô biên",
  "Ngũ tình vô địch",
  "Ma đạo hoành hành",
  "Ma đao đoạn tình",
  "Ma đạp thất tinh",
  "Quần ma loạn vũ",
];
